/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PomocRouteImport } from './routes/pomoc'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ModulyRouteImport } from './routes/moduly'
import { Route as EdziennikRouteImport } from './routes/edziennik'
import { Route as EDziennikRouteImport } from './routes/e-dziennik'
import { Route as DokumentyRouteImport } from './routes/dokumenty'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CentrumDokumentowRouteImport } from './routes/centrum-dokumentow'
import { Route as CennikRouteImport } from './routes/cennik'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifySerialRouteImport } from './routes/verify.$serial'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as DemoStudentRouteImport } from './routes/demo.student'
import { Route as DemoParentRouteImport } from './routes/demo.parent'
import { Route as DemoAdminRouteImport } from './routes/demo.admin'
import { Route as AuthTeacherRouteImport } from './routes/auth.teacher'
import { Route as AuthStudentRouteImport } from './routes/auth.student'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthParentRouteImport } from './routes/auth.parent'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as ApiDocumentTemplatesRouteImport } from './routes/api/document-templates'
import { Route as ApiAiTutorStreamRouteImport } from './routes/api/ai-tutor-stream'
import { Route as ApiAiHealthRouteImport } from './routes/api/ai-health'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated.teacher'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated.parent'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as StudentExamAttemptIdRouteImport } from './routes/student.exam.$attemptId'
import { Route as ApiAdminFixAuthRouteImport } from './routes/api/admin/fix-auth'

const PomocRoute = PomocRouteImport.update({
  id: '/pomoc',
  path: '/pomoc',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulyRoute = ModulyRouteImport.update({
  id: '/moduly',
  path: '/moduly',
  getParentRoute: () => rootRouteImport,
} as any)
const EdziennikRoute = EdziennikRouteImport.update({
  id: '/edziennik',
  path: '/edziennik',
  getParentRoute: () => rootRouteImport,
} as any)
const EDziennikRoute = EDziennikRouteImport.update({
  id: '/e-dziennik',
  path: '/e-dziennik',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentyRoute = DokumentyRouteImport.update({
  id: '/dokumenty',
  path: '/dokumenty',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CentrumDokumentowRoute = CentrumDokumentowRouteImport.update({
  id: '/centrum-dokumentow',
  path: '/centrum-dokumentow',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikRoute = CennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySerialRoute = VerifySerialRouteImport.update({
  id: '/verify/$serial',
  path: '/verify/$serial',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStudentRoute = DemoStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DemoRoute,
} as any)
const DemoParentRoute = DemoParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAdminRoute = DemoAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DemoRoute,
} as any)
const AuthTeacherRoute = AuthTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthParentRoute = AuthParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const ApiDocumentTemplatesRoute = ApiDocumentTemplatesRouteImport.update({
  id: '/api/document-templates',
  path: '/api/document-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTutorStreamRoute = ApiAiTutorStreamRouteImport.update({
  id: '/api/ai-tutor-stream',
  path: '/api/ai-tutor-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiHealthRoute = ApiAiHealthRouteImport.update({
  id: '/api/ai-health',
  path: '/api/ai-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const StudentExamAttemptIdRoute = StudentExamAttemptIdRouteImport.update({
  id: '/student/exam/$attemptId',
  path: '/student/exam/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFixAuthRoute = ApiAdminFixAuthRouteImport.update({
  id: '/api/admin/fix-auth',
  path: '/api/admin/fix-auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cennik': typeof CennikRoute
  '/centrum-dokumentow': typeof CentrumDokumentowRoute
  '/demo': typeof DemoRouteWithChildren
  '/dokumenty': typeof DokumentyRoute
  '/e-dziennik': typeof EDziennikRoute
  '/edziennik': typeof EdziennikRoute
  '/moduly': typeof ModulyRoute
  '/onboarding': typeof OnboardingRoute
  '/pomoc': typeof PomocRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/parent': typeof AuthenticatedParentRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/api/ai-health': typeof ApiAiHealthRoute
  '/api/ai-tutor-stream': typeof ApiAiTutorStreamRoute
  '/api/document-templates': typeof ApiDocumentTemplatesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/parent': typeof AuthParentRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student': typeof AuthStudentRoute
  '/auth/teacher': typeof AuthTeacherRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/student': typeof DemoStudentRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/verify/$serial': typeof VerifySerialRoute
  '/api/admin/fix-auth': typeof ApiAdminFixAuthRoute
  '/student/exam/$attemptId': typeof StudentExamAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cennik': typeof CennikRoute
  '/centrum-dokumentow': typeof CentrumDokumentowRoute
  '/demo': typeof DemoRouteWithChildren
  '/dokumenty': typeof DokumentyRoute
  '/e-dziennik': typeof EDziennikRoute
  '/edziennik': typeof EdziennikRoute
  '/moduly': typeof ModulyRoute
  '/onboarding': typeof OnboardingRoute
  '/pomoc': typeof PomocRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/parent': typeof AuthenticatedParentRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/api/ai-health': typeof ApiAiHealthRoute
  '/api/ai-tutor-stream': typeof ApiAiTutorStreamRoute
  '/api/document-templates': typeof ApiDocumentTemplatesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/parent': typeof AuthParentRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student': typeof AuthStudentRoute
  '/auth/teacher': typeof AuthTeacherRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/student': typeof DemoStudentRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/verify/$serial': typeof VerifySerialRoute
  '/api/admin/fix-auth': typeof ApiAdminFixAuthRoute
  '/student/exam/$attemptId': typeof StudentExamAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/cennik': typeof CennikRoute
  '/centrum-dokumentow': typeof CentrumDokumentowRoute
  '/demo': typeof DemoRouteWithChildren
  '/dokumenty': typeof DokumentyRoute
  '/e-dziennik': typeof EDziennikRoute
  '/edziennik': typeof EdziennikRoute
  '/moduly': typeof ModulyRoute
  '/onboarding': typeof OnboardingRoute
  '/pomoc': typeof PomocRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/parent': typeof AuthenticatedParentRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/api/ai-health': typeof ApiAiHealthRoute
  '/api/ai-tutor-stream': typeof ApiAiTutorStreamRoute
  '/api/document-templates': typeof ApiDocumentTemplatesRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/parent': typeof AuthParentRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student': typeof AuthStudentRoute
  '/auth/teacher': typeof AuthTeacherRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/student': typeof DemoStudentRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/verify/$serial': typeof VerifySerialRoute
  '/api/admin/fix-auth': typeof ApiAdminFixAuthRoute
  '/student/exam/$attemptId': typeof StudentExamAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cennik'
    | '/centrum-dokumentow'
    | '/demo'
    | '/dokumenty'
    | '/e-dziennik'
    | '/edziennik'
    | '/moduly'
    | '/onboarding'
    | '/pomoc'
    | '/admin'
    | '/parent'
    | '/teacher'
    | '/api/ai-health'
    | '/api/ai-tutor-stream'
    | '/api/document-templates'
    | '/auth/admin'
    | '/auth/callback'
    | '/auth/parent'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/student'
    | '/auth/teacher'
    | '/demo/admin'
    | '/demo/parent'
    | '/demo/student'
    | '/student/dashboard'
    | '/verify/$serial'
    | '/api/admin/fix-auth'
    | '/student/exam/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cennik'
    | '/centrum-dokumentow'
    | '/demo'
    | '/dokumenty'
    | '/e-dziennik'
    | '/edziennik'
    | '/moduly'
    | '/onboarding'
    | '/pomoc'
    | '/admin'
    | '/parent'
    | '/teacher'
    | '/api/ai-health'
    | '/api/ai-tutor-stream'
    | '/api/document-templates'
    | '/auth/admin'
    | '/auth/callback'
    | '/auth/parent'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/student'
    | '/auth/teacher'
    | '/demo/admin'
    | '/demo/parent'
    | '/demo/student'
    | '/student/dashboard'
    | '/verify/$serial'
    | '/api/admin/fix-auth'
    | '/student/exam/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cennik'
    | '/centrum-dokumentow'
    | '/demo'
    | '/dokumenty'
    | '/e-dziennik'
    | '/edziennik'
    | '/moduly'
    | '/onboarding'
    | '/pomoc'
    | '/_authenticated/admin'
    | '/_authenticated/parent'
    | '/_authenticated/teacher'
    | '/api/ai-health'
    | '/api/ai-tutor-stream'
    | '/api/document-templates'
    | '/auth/admin'
    | '/auth/callback'
    | '/auth/parent'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/student'
    | '/auth/teacher'
    | '/demo/admin'
    | '/demo/parent'
    | '/demo/student'
    | '/student/dashboard'
    | '/verify/$serial'
    | '/api/admin/fix-auth'
    | '/student/exam/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CennikRoute: typeof CennikRoute
  CentrumDokumentowRoute: typeof CentrumDokumentowRoute
  DemoRoute: typeof DemoRouteWithChildren
  DokumentyRoute: typeof DokumentyRoute
  EDziennikRoute: typeof EDziennikRoute
  EdziennikRoute: typeof EdziennikRoute
  ModulyRoute: typeof ModulyRoute
  OnboardingRoute: typeof OnboardingRoute
  PomocRoute: typeof PomocRoute
  ApiAiHealthRoute: typeof ApiAiHealthRoute
  ApiAiTutorStreamRoute: typeof ApiAiTutorStreamRoute
  ApiDocumentTemplatesRoute: typeof ApiDocumentTemplatesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  VerifySerialRoute: typeof VerifySerialRoute
  ApiAdminFixAuthRoute: typeof ApiAdminFixAuthRoute
  StudentExamAttemptIdRoute: typeof StudentExamAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pomoc': {
      id: '/pomoc'
      path: '/pomoc'
      fullPath: '/pomoc'
      preLoaderRoute: typeof PomocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moduly': {
      id: '/moduly'
      path: '/moduly'
      fullPath: '/moduly'
      preLoaderRoute: typeof ModulyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edziennik': {
      id: '/edziennik'
      path: '/edziennik'
      fullPath: '/edziennik'
      preLoaderRoute: typeof EdziennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-dziennik': {
      id: '/e-dziennik'
      path: '/e-dziennik'
      fullPath: '/e-dziennik'
      preLoaderRoute: typeof EDziennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenty': {
      id: '/dokumenty'
      path: '/dokumenty'
      fullPath: '/dokumenty'
      preLoaderRoute: typeof DokumentyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centrum-dokumentow': {
      id: '/centrum-dokumentow'
      path: '/centrum-dokumentow'
      fullPath: '/centrum-dokumentow'
      preLoaderRoute: typeof CentrumDokumentowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik': {
      id: '/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof CennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$serial': {
      id: '/verify/$serial'
      path: '/verify/$serial'
      fullPath: '/verify/$serial'
      preLoaderRoute: typeof VerifySerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/student': {
      id: '/demo/student'
      path: '/student'
      fullPath: '/demo/student'
      preLoaderRoute: typeof DemoStudentRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/parent': {
      id: '/demo/parent'
      path: '/parent'
      fullPath: '/demo/parent'
      preLoaderRoute: typeof DemoParentRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/admin': {
      id: '/demo/admin'
      path: '/admin'
      fullPath: '/demo/admin'
      preLoaderRoute: typeof DemoAdminRouteImport
      parentRoute: typeof DemoRoute
    }
    '/auth/teacher': {
      id: '/auth/teacher'
      path: '/teacher'
      fullPath: '/auth/teacher'
      preLoaderRoute: typeof AuthTeacherRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/student': {
      id: '/auth/student'
      path: '/student'
      fullPath: '/auth/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/parent': {
      id: '/auth/parent'
      path: '/parent'
      fullPath: '/auth/parent'
      preLoaderRoute: typeof AuthParentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/document-templates': {
      id: '/api/document-templates'
      path: '/api/document-templates'
      fullPath: '/api/document-templates'
      preLoaderRoute: typeof ApiDocumentTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-tutor-stream': {
      id: '/api/ai-tutor-stream'
      path: '/api/ai-tutor-stream'
      fullPath: '/api/ai-tutor-stream'
      preLoaderRoute: typeof ApiAiTutorStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-health': {
      id: '/api/ai-health'
      path: '/api/ai-health'
      fullPath: '/api/ai-health'
      preLoaderRoute: typeof ApiAiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/student/exam/$attemptId': {
      id: '/student/exam/$attemptId'
      path: '/student/exam/$attemptId'
      fullPath: '/student/exam/$attemptId'
      preLoaderRoute: typeof StudentExamAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fix-auth': {
      id: '/api/admin/fix-auth'
      path: '/api/admin/fix-auth'
      fullPath: '/api/admin/fix-auth'
      preLoaderRoute: typeof ApiAdminFixAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedParentRoute: typeof AuthenticatedParentRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedParentRoute: AuthenticatedParentRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthParentRoute: typeof AuthParentRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthStudentRoute: typeof AuthStudentRoute
  AuthTeacherRoute: typeof AuthTeacherRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthParentRoute: AuthParentRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthStudentRoute: AuthStudentRoute,
  AuthTeacherRoute: AuthTeacherRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DemoRouteChildren {
  DemoAdminRoute: typeof DemoAdminRoute
  DemoParentRoute: typeof DemoParentRoute
  DemoStudentRoute: typeof DemoStudentRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAdminRoute: DemoAdminRoute,
  DemoParentRoute: DemoParentRoute,
  DemoStudentRoute: DemoStudentRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CennikRoute: CennikRoute,
  CentrumDokumentowRoute: CentrumDokumentowRoute,
  DemoRoute: DemoRouteWithChildren,
  DokumentyRoute: DokumentyRoute,
  EDziennikRoute: EDziennikRoute,
  EdziennikRoute: EdziennikRoute,
  ModulyRoute: ModulyRoute,
  OnboardingRoute: OnboardingRoute,
  PomocRoute: PomocRoute,
  ApiAiHealthRoute: ApiAiHealthRoute,
  ApiAiTutorStreamRoute: ApiAiTutorStreamRoute,
  ApiDocumentTemplatesRoute: ApiDocumentTemplatesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  VerifySerialRoute: VerifySerialRoute,
  ApiAdminFixAuthRoute: ApiAdminFixAuthRoute,
  StudentExamAttemptIdRoute: StudentExamAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
