/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DokumentyRouteImport } from './routes/dokumenty'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifySerialRouteImport } from './routes/verify.$serial'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as DemoStudentRouteImport } from './routes/demo.student'
import { Route as DemoParentRouteImport } from './routes/demo.parent'
import { Route as DemoAdminRouteImport } from './routes/demo.admin'
import { Route as AuthTeacherRouteImport } from './routes/auth.teacher'
import { Route as AuthStudentRouteImport } from './routes/auth.student'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthParentRouteImport } from './routes/auth.parent'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthAdminRouteImport } from './routes/auth.admin'
import { Route as ApiAiTutorStreamRouteImport } from './routes/api/ai-tutor-stream'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated.teacher'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated.parent'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as StudentExamAttemptIdRouteImport } from './routes/student.exam.$attemptId'
import { Route as ApiAdminFixAuthRouteImport } from './routes/api/admin/fix-auth'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentyRoute = DokumentyRouteImport.update({
  id: '/dokumenty',
  path: '/dokumenty',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySerialRoute = VerifySerialRouteImport.update({
  id: '/verify/$serial',
  path: '/verify/$serial',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStudentRoute = DemoStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => DemoRoute,
} as any)
const DemoParentRoute = DemoParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAdminRoute = DemoAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DemoRoute,
} as any)
const AuthTeacherRoute = AuthTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthRoute,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthParentRoute = AuthParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAiTutorStreamRoute = ApiAiTutorStreamRouteImport.update({
  id: '/api/ai-tutor-stream',
  path: '/api/ai-tutor-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const StudentExamAttemptIdRoute = StudentExamAttemptIdRouteImport.update({
  id: '/student/exam/$attemptId',
  path: '/student/exam/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFixAuthRoute = ApiAdminFixAuthRouteImport.update({
  id: '/api/admin/fix-auth',
  path: '/api/admin/fix-auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/dokumenty': typeof DokumentyRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/parent': typeof AuthenticatedParentRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/api/ai-tutor-stream': typeof ApiAiTutorStreamRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/parent': typeof AuthParentRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student': typeof AuthStudentRoute
  '/auth/teacher': typeof AuthTeacherRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/student': typeof DemoStudentRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/verify/$serial': typeof VerifySerialRoute
  '/api/admin/fix-auth': typeof ApiAdminFixAuthRoute
  '/student/exam/$attemptId': typeof StudentExamAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/dokumenty': typeof DokumentyRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/parent': typeof AuthenticatedParentRoute
  '/teacher': typeof AuthenticatedTeacherRoute
  '/api/ai-tutor-stream': typeof ApiAiTutorStreamRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/parent': typeof AuthParentRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student': typeof AuthStudentRoute
  '/auth/teacher': typeof AuthTeacherRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/student': typeof DemoStudentRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/verify/$serial': typeof VerifySerialRoute
  '/api/admin/fix-auth': typeof ApiAdminFixAuthRoute
  '/student/exam/$attemptId': typeof StudentExamAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/demo': typeof DemoRouteWithChildren
  '/dokumenty': typeof DokumentyRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/parent': typeof AuthenticatedParentRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
  '/api/ai-tutor-stream': typeof ApiAiTutorStreamRoute
  '/auth/admin': typeof AuthAdminRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/parent': typeof AuthParentRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/student': typeof AuthStudentRoute
  '/auth/teacher': typeof AuthTeacherRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/student': typeof DemoStudentRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/verify/$serial': typeof VerifySerialRoute
  '/api/admin/fix-auth': typeof ApiAdminFixAuthRoute
  '/student/exam/$attemptId': typeof StudentExamAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/dokumenty'
    | '/onboarding'
    | '/admin'
    | '/parent'
    | '/teacher'
    | '/api/ai-tutor-stream'
    | '/auth/admin'
    | '/auth/callback'
    | '/auth/parent'
    | '/auth/reset-password'
    | '/auth/student'
    | '/auth/teacher'
    | '/demo/admin'
    | '/demo/parent'
    | '/demo/student'
    | '/student/dashboard'
    | '/verify/$serial'
    | '/api/admin/fix-auth'
    | '/student/exam/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/dokumenty'
    | '/onboarding'
    | '/admin'
    | '/parent'
    | '/teacher'
    | '/api/ai-tutor-stream'
    | '/auth/admin'
    | '/auth/callback'
    | '/auth/parent'
    | '/auth/reset-password'
    | '/auth/student'
    | '/auth/teacher'
    | '/demo/admin'
    | '/demo/parent'
    | '/demo/student'
    | '/student/dashboard'
    | '/verify/$serial'
    | '/api/admin/fix-auth'
    | '/student/exam/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/dokumenty'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/parent'
    | '/_authenticated/teacher'
    | '/api/ai-tutor-stream'
    | '/auth/admin'
    | '/auth/callback'
    | '/auth/parent'
    | '/auth/reset-password'
    | '/auth/student'
    | '/auth/teacher'
    | '/demo/admin'
    | '/demo/parent'
    | '/demo/student'
    | '/student/dashboard'
    | '/verify/$serial'
    | '/api/admin/fix-auth'
    | '/student/exam/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DemoRoute: typeof DemoRouteWithChildren
  DokumentyRoute: typeof DokumentyRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAiTutorStreamRoute: typeof ApiAiTutorStreamRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  VerifySerialRoute: typeof VerifySerialRoute
  ApiAdminFixAuthRoute: typeof ApiAdminFixAuthRoute
  StudentExamAttemptIdRoute: typeof StudentExamAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumenty': {
      id: '/dokumenty'
      path: '/dokumenty'
      fullPath: '/dokumenty'
      preLoaderRoute: typeof DokumentyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$serial': {
      id: '/verify/$serial'
      path: '/verify/$serial'
      fullPath: '/verify/$serial'
      preLoaderRoute: typeof VerifySerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/student': {
      id: '/demo/student'
      path: '/student'
      fullPath: '/demo/student'
      preLoaderRoute: typeof DemoStudentRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/parent': {
      id: '/demo/parent'
      path: '/parent'
      fullPath: '/demo/parent'
      preLoaderRoute: typeof DemoParentRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/admin': {
      id: '/demo/admin'
      path: '/admin'
      fullPath: '/demo/admin'
      preLoaderRoute: typeof DemoAdminRouteImport
      parentRoute: typeof DemoRoute
    }
    '/auth/teacher': {
      id: '/auth/teacher'
      path: '/teacher'
      fullPath: '/auth/teacher'
      preLoaderRoute: typeof AuthTeacherRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/student': {
      id: '/auth/student'
      path: '/student'
      fullPath: '/auth/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/parent': {
      id: '/auth/parent'
      path: '/parent'
      fullPath: '/auth/parent'
      preLoaderRoute: typeof AuthParentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/admin': {
      id: '/auth/admin'
      path: '/admin'
      fullPath: '/auth/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/ai-tutor-stream': {
      id: '/api/ai-tutor-stream'
      path: '/api/ai-tutor-stream'
      fullPath: '/api/ai-tutor-stream'
      preLoaderRoute: typeof ApiAiTutorStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/student/exam/$attemptId': {
      id: '/student/exam/$attemptId'
      path: '/student/exam/$attemptId'
      fullPath: '/student/exam/$attemptId'
      preLoaderRoute: typeof StudentExamAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fix-auth': {
      id: '/api/admin/fix-auth'
      path: '/api/admin/fix-auth'
      fullPath: '/api/admin/fix-auth'
      preLoaderRoute: typeof ApiAdminFixAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedParentRoute: typeof AuthenticatedParentRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedParentRoute: AuthenticatedParentRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthParentRoute: typeof AuthParentRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthStudentRoute: typeof AuthStudentRoute
  AuthTeacherRoute: typeof AuthTeacherRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthParentRoute: AuthParentRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthStudentRoute: AuthStudentRoute,
  AuthTeacherRoute: AuthTeacherRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DemoRouteChildren {
  DemoAdminRoute: typeof DemoAdminRoute
  DemoParentRoute: typeof DemoParentRoute
  DemoStudentRoute: typeof DemoStudentRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAdminRoute: DemoAdminRoute,
  DemoParentRoute: DemoParentRoute,
  DemoStudentRoute: DemoStudentRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DemoRoute: DemoRouteWithChildren,
  DokumentyRoute: DokumentyRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAiTutorStreamRoute: ApiAiTutorStreamRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  VerifySerialRoute: VerifySerialRoute,
  ApiAdminFixAuthRoute: ApiAdminFixAuthRoute,
  StudentExamAttemptIdRoute: StudentExamAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
