
INSERT INTO public.question_categories (name, slug, color, icon, description) VALUES
('Algebra', 'algebra', 'cyan', '🔢', 'Równania, układy, wielomiany, funkcje liniowe i kwadratowe'),
('Geometria', 'geometria', 'sky', '📐', 'Planimetria, stereometria, trygonometria'),
('Analiza matematyczna', 'analiza', 'blue', '∫', 'Granice, pochodne, całki, ciągi'),
('Statystyka i prawdopodobieństwo', 'statystyka', 'indigo', '📊', 'Kombinatoryka, rozkłady, średnie'),
('Logika i teoria mnogości', 'logika', 'violet', '∀', 'Zdania, kwantyfikatory, zbiory'),
('Gramatyka polska', 'gramatyka-pl', 'rose', '✍️', 'Fleksja, składnia, ortografia, interpunkcja'),
('Literatura polska', 'literatura-pl', 'pink', '📚', 'Epoki, motywy, lektury obowiązkowe'),
('Historia Polski', 'historia-pl', 'amber', '🦅', 'Od Mieszka I do III RP'),
('Historia powszechna', 'historia-pow', 'orange', '🌍', 'Starożytność, średniowiecze, nowożytność, XX wiek'),
('Historia sztuki', 'historia-sztuki', 'fuchsia', '🎨', 'Style, dzieła, twórcy'),
('Geografia fizyczna', 'geo-fiz', 'emerald', '🏔️', 'Klimat, ukształtowanie, hydrosfera'),
('Geografia społeczno-ekonomiczna', 'geo-spol', 'green', '🏭', 'Demografia, gospodarka, transport'),
('Anatomia człowieka', 'anatomia', 'red', '🫀', 'Układy ciała, narządy, fizjologia'),
('Genetyka', 'genetyka', 'green', '🧬', 'DNA, dziedziczenie, mutacje'),
('Ekologia', 'ekologia', 'emerald', '🌿', 'Ekosystemy, biosfera, ochrona środowiska'),
('Botanika', 'botanika', 'green', '🌱', 'Rośliny, fotosynteza, systematyka'),
('Zoologia', 'zoologia', 'amber', '🦌', 'Zwierzęta, klasyfikacja, ewolucja'),
('Chemia organiczna', 'chemia-org', 'violet', '⚗️', 'Węglowodory, alkohole, kwasy, biocząsteczki'),
('Chemia nieorganiczna', 'chemia-nieorg', 'fuchsia', '🧪', 'Pierwiastki, związki, reakcje'),
('Mechanika', 'mechanika', 'sky', '⚙️', 'Kinematyka, dynamika, energia'),
('Elektryczność i magnetyzm', 'elektrycznosc', 'yellow', '⚡', 'Prąd, pola, obwody'),
('Optyka', 'optyka', 'violet', '🔭', 'Światło, soczewki, fale'),
('Fizyka kwantowa', 'fizyka-kw', 'indigo', '⚛️', 'Atom, cząstki elementarne'),
('Astronomia', 'astronomia', 'indigo', '🌌', 'Układ Słoneczny, gwiazdy, kosmos'),
('Język niemiecki — gramatyka', 'de-gram', 'orange', '🇩🇪', 'Deklinacja, czasy, składnia'),
('Język angielski — gramatyka', 'en-gram', 'red', '🇬🇧', 'Tenses, conditionals, modals'),
('Język angielski — słownictwo', 'en-voc', 'rose', '💬', 'Vocabulary, idioms, phrasal verbs'),
('Język hiszpański', 'es', 'amber', '🇪🇸', 'Hiszpański podstawy i średniozaawansowany'),
('Język francuski', 'fr', 'blue', '🇫🇷', 'Francuski A1-B2'),
('Język rosyjski', 'ru', 'red', '🇷🇺', 'Rosyjski podstawy'),
('Łacina', 'lacina', 'amber', '📜', 'Deklinacje, koniugacje, sentencje'),
('WOS — ustrój RP', 'wos-ustroj', 'yellow', '⚖️', 'Konstytucja, instytucje państwa'),
('WOS — UE i organizacje', 'wos-ue', 'blue', '🇪🇺', 'Unia Europejska, NATO, ONZ'),
('Ekonomia', 'ekonomia', 'emerald', '💰', 'Mikro i makroekonomia, finanse'),
('Przedsiębiorczość', 'przedsiebiorczosc', 'green', '💼', 'Biznes, rynek pracy, marketing'),
('Religia', 'religia', 'amber', '✝️', 'Teologia, etyka chrześcijańska'),
('Etyka', 'etyka', 'rose', '🤝', 'Filozofia moralna, dylematy etyczne'),
('Algorytmy i struktury danych', 'algorytmy', 'cyan', '🧮', 'Sortowanie, wyszukiwanie, drzewa, grafy'),
('Python', 'python', 'green', '🐍', 'Programowanie w Pythonie'),
('JavaScript / TypeScript', 'js-ts', 'yellow', '📜', 'Web development, frameworki'),
('Java', 'java', 'orange', '☕', 'OOP, kolekcje, wątki'),
('C / C++', 'c-cpp', 'blue', '⚡', 'Wskaźniki, pamięć, STL'),
('SQL i bazy danych', 'sql', 'emerald', '🗄️', 'Zapytania, JOIN-y, indeksy, normalizacja'),
('HTML / CSS', 'html-css', 'orange', '🎨', 'Web fundamentals, layout, animacje'),
('Cyberbezpieczeństwo', 'cyberbezp', 'red', '🛡️', 'Hacking etyczny, kryptografia, zagrożenia'),
('Sieci komputerowe — zaawansowane', 'sieci-adv', 'blue', '🌐', 'TCP/IP, routing, VLAN, OSI'),
('DevOps i chmura', 'devops', 'violet', '☁️', 'Docker, Kubernetes, CI/CD, AWS'),
('Machine Learning', 'ml', 'fuchsia', '🤖', 'Modele, regresja, sieci neuronowe'),
('Grafika komputerowa', 'grafika', 'pink', '🖼️', 'Photoshop, Illustrator, projektowanie'),
('Muzyka', 'muzyka', 'violet', '🎵', 'Teoria muzyki, kompozytorzy, instrumenty'),
('Plastyka', 'plastyka', 'rose', '🖌️', 'Techniki, kompozycja, kolor'),
('Wychowanie fizyczne', 'wf', 'green', '⚽', 'Sport, anatomia ruchu, zasady gier'),
('Edukacja dla bezpieczeństwa', 'edb', 'red', '🚨', 'Pierwsza pomoc, obronność, zagrożenia'),
('Ochrona środowiska', 'srodowisko', 'emerald', '♻️', 'Recykling, klimat, zrównoważony rozwój'),
('Mechatronika', 'mechatronika', 'cyan', '🤖', 'Robotyka, sensory, automatyka'),
('Elektronika', 'elektronika', 'yellow', '🔌', 'Elementy, układy, schematy')
ON CONFLICT (slug) DO NOTHING;
